#!/bin/bash -p
# Copyright (c) 2017 Timothée Feuillet
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# restore the prig env
. "$prig_directory/$gbl_opt_prig_command_dir/cmd/generator_restore_env"

(( $# >= 2 )) || die "wrong number of args"
output_file="$1"
template_file="$2"

shift
shift

# check that the output file is correct
check_path "$output_file"
check_path_inside "$generator_directory/$template_file" "$generator_directory"

[ -f "$generator_directory/$template_file" ] || die "template file '$generator_directory/$template_file' does not exists"


log 'generate:' $output_file '<-' $template_file

. "$prig_directory/$gbl_opt_prig_command_dir/cmd/generator_env/render_template" "$template_file" "$@" > "$output_file"
